site_name: dtspy - A Python client for the Data Transfer Service

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Overview: index.md
  - API reference: api.md
  - Example scripts: examples.md
